# Uncertainty Forest (UF) Demo
This demo provides the basic use cases of the `uncertainty_forest` module.

In [1]:
import numpy as np
from uncertainty_forest.uncertainty_forest import UncertaintyForest

## Hyperparameter Specification
Random forest hyperparameters such as minimum leaf size and maximum depth can be specified by the UF constructor.

In [5]:
# Notation from the current paper. 
min_samples_leaf = 1 # k
max_features = None  # m
n_estimators = 200   # B
max_samples = .5     # s // 2
bootstrap = False    # Whether to subsample with replacement.
parallel = True

uf = UncertaintyForest(         
    min_samples_leaf = min_samples_leaf,    
    max_features = max_features,   
    n_estimators = n_estimators,   
    max_samples = max_samples,   
    bootstrap = bootstrap,
    parallel = parallel
)

In [6]:
# Or, you can just use the defaults.
uf = UncertaintyForest()

## Estimate the Conditional Probability of `Y` given `X = x`
Use `X_train` and `y_train` to estimate the posterior, and evaluate this posterior at `X_eval`.

In [7]:
n_class = 25
d = 10
classes = [-1, 0, 1]

X_train = np.concatenate([np.random.multivariate_normal(k*np.ones(d), np.eye(d), n_class) for k in classes])
y_train = np.concatenate([k*np.ones(n_class) for k in classes])
print(X_train.shape)
print(y_train.shape)

X_eval = np.array([c*np.ones(d) for c in range(-2, 3)])
print(X_eval)

(75, 10)
(75,)
[[-2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]


In [8]:
uf.fit(X_train, y_train)
cond_probability = uf.predict_proba(X_eval)
print("P(Y|X = x) for x in X_eval:")
print(cond_probability)

P(Y|X = x) for x in X_eval:
[[0.79480619 0.13756862 0.06762519]
 [0.74023584 0.17754233 0.08222183]
 [0.29167247 0.49790124 0.21042628]
 [0.07731687 0.17532126 0.74736187]
 [0.06672125 0.11776289 0.81551586]]


## Estimate the Conditional Entropy
`H(Y | X)` is also computed using the evaluation set `X_eval`.

In [9]:
cond_entropy = uf.estimate_cond_entropy(X_eval)
print("0 <= H(Y|X) = %f <= log2(3) = %f" % (cond_entropy, np.log2(3.0)))

0 <= H(Y|X) = 1.075318 <= log2(3) = 1.584963


# Estimate the mutual information
Mutual information can be estimated with the exact same protocol as conditional entropy, with `estimate_mutual_info`.

In [10]:
mutual_info = uf.estimate_mutual_info(X_eval)
print("I(X, Y) = %f" % mutual_info)

I(X, Y) = 0.509644
